### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#7]
Integrate this map:
https://www.internetsociety.org/map/global-internet-report/ 
(with citation)
rather than the google map.

**Comment by tati** [comment]
v1 fixed with https://github.com/thenextbilliononline/thenextbillion.online/pull/19

1) not sure about size 2) scroll is a big weird 3) maybe we want to customize more, but right now this is just their iframe and I am not 100% how much more I can change

![screen shot 2017-04-26 at 8 55 44 pm](https://cloud.githubusercontent.com/assets/12241872/25463278/2663743a-2ac3-11e7-820f-c721a66d18fd.png)

**Comment by simplymathematics** [comment]
Let's take it off the main page for the new design and make it into a blog post. Context and analysis probably make this tool more useful anyway.
